export const traders = [
  {
    owner: '1',
    name: 'Cypher',
    nft_mint: 'mint1',
    elo: 1850,
    wins: 120,
    losses: 45,
    xp: 8500,
    tier: 'Diamond',
    tierColor: 'text-cyan-400',
    skins: [],
    last_daily_claim: 0,
    image: 'trader-1',
  },
  {
    owner: '2',
    name: 'Blitz',
    nft_mint: 'mint2',
    elo: 1600,
    wins: 95,
    losses: 60,
    xp: 6200,
    tier: 'Gold',
    tierColor: 'text-yellow-400',
    skins: [],
    last_daily_claim: 0,
    image: 'trader-2',
  },
  {
    owner: '3',
    name: 'Shade',
    nft_mint: 'mint3',
    elo: 1300,
    wins: 70,
    losses: 55,
    xp: 4100,
    tier: 'Silver',
    tierColor: 'text-slate-300',
    skins: [],
    last_daily_claim: 0,
    image: 'trader-3',
  },
  {
    owner: '4',
    name: 'Rook',
    nft_mint: 'mint4',
    elo: 1100,
    wins: 40,
    losses: 30,
    xp: 2500,
    tier: 'Bronze',
    tierColor: 'text-amber-600',
    skins: [],
    last_daily_claim: 0,
    image: 'trader-4',
  },
];

export const leagues = [
  {
    id: 'BRONZE_SEASON_1',
    name: 'Bronze League',
    elo_min: 0,
    elo_max: 1199,
    entry_fee: 0,
    rewards: '$100 Prize Pool',
  },
  {
    id: 'SILVER_SEASON_1',
    name: 'Silver League',
    elo_min: 1200,
    elo_max: 1449,
    entry_fee: 10,
    rewards: '$500 Prize Pool',
  },
  {
    id: 'GOLD_SEASON_1',
    name: 'Gold League',
    elo_min: 1450,
    elo_max: 1699,
    entry_fee: 25,
    rewards: '$1,000 Prize Pool',
  },
  {
    id: 'DIAMOND_SEASON_1',
    name: 'Diamond League',
    elo_min: 1700,
    elo_max: 9999,
    entry_fee: 50,
    rewards: '$5,000 Prize Pool',
  },
];

export const leaderboardData = [
  { rank: 1, name: 'Cypher', elo: 1850, wins: 120, losses: 45 },
  { rank: 2, name: 'Nexus', elo: 1825, wins: 115, losses: 48 },
  { rank: 3, name: 'Vortex', elo: 1790, wins: 110, losses: 50 },
  { rank: 4, 'name': 'Blitz', 'elo': 1600, 'wins': 95, 'losses': 60 },
  { rank: 5, 'name': 'Aura', 'elo': 1580, 'wins': 90, 'losses': 55 },
  { rank: 6, 'name': 'Reverb', 'elo': 1550, 'wins': 88, 'losses': 52 },
  { rank: 7, 'name': 'Shade', 'elo': 1300, 'wins': 70, 'losses': 55 },
  { rank: 8, 'name': 'Echo', 'elo': 1250, 'wins': 65, 'losses': 50 },
  { rank: 9, 'name': 'Rook', 'elo': 1100, 'wins': 40, 'losses': 30 },
  { rank: 10, 'name': 'Jolt', 'elo': 1050, 'wins': 35, 'losses': 25 },
];

export const learningModules = [
  {
    id: 'intro-to-fluxion',
    title: 'Introduction to Fluxion Arena',
    content: 'Learn the basics of Fluxion Arena, including game mechanics, trader cards, and the ELO system. This module covers everything you need to know to start your journey.',
  },
  {
    id: 'advanced-strategies',
    title: 'Advanced Battle Strategies',
    content: 'Dive deep into advanced tactics, counter-plays, and team compositions. Understand how to leverage your trader\'s abilities to dominate the arena.',
  },
  {
    id: 'elo-and-leagues',
    title: 'Understanding ELO and Leagues',
    content: 'A comprehensive guide to the ELO rating system, league structure, and seasonal progression. Learn how to climb the ranks and earn exclusive rewards.',
  },
  {
    id: 'economy-and-nfts',
    title: 'The $FLXN Economy & NFTs',
    content: 'Explore the tokenomics of $FLXN, the utility of Trader Card NFTs, and how to manage your on-chain assets within the Fluxion Arena ecosystem.',
  },
];
